/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WPPublisherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  wpUrl: "",
  wpUsername: "",
  wpPassword: "",
  defaultTemplatePath: "",
  publishFolder: "",
  autoApplyTemplateOnNewNotes: true,
  syncOnSave: true,
  hotkeyPublish: null,
  hotkeyDraft: null
};
var HERMES_PLUGIN_VERSION = "1.0.3-hermes.1";
var DEFAULT_WP_POST_TEMPLATE = `---
category: 
excerpt: 
status: draft
wp-id: 
---
`;
var wait = (ms) => new Promise((resolve) => window.setTimeout(resolve, ms));
function hotkeyLabel(hk) {
  if (!hk) return "Not set";
  const parts = [...hk.modifiers, hk.key];
  return parts.join(" + ");
}
function eventToHotkey(e) {
  if (["Control", "Shift", "Alt", "Meta"].includes(e.key)) return null;
  const modifiers = [];
  if (e.ctrlKey) modifiers.push("Ctrl");
  if (e.altKey) modifiers.push("Alt");
  if (e.shiftKey) modifiers.push("Shift");
  if (e.metaKey) modifiers.push("Meta");
  if (modifiers.length === 0) return null;
  const key = e.key.length === 1 ? e.key.toUpperCase() : e.key;
  return { modifiers, key };
}
function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function mdToHtml(md) {
  md = md.replace(/%%[\s\S]*?%%/g, "").trim();
  const lines = md.split("\n");
  const htmlLines = [];
  let inUl = false;
  let inOl = false;
  let inCodeBlock = false;
  let codeLang = "";
  let codeBuffer = [];
  const closeLists = () => {
    if (inUl) {
      htmlLines.push("</ul>");
      inUl = false;
    }
    if (inOl) {
      htmlLines.push("</ol>");
      inOl = false;
    }
  };
  const youtubeEmbed = (url) => {
    const match = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([A-Za-z0-9_-]+)/);
    return match ? `<div class="wp-embed-responsive"><iframe src="https://www.youtube.com/embed/${match[1]}" frameborder="0" allowfullscreen></iframe></div>` : null;
  };
  const vimeoEmbed = (url) => {
    const match = url.match(/vimeo\.com\/(\d+)/);
    return match ? `<div class="wp-embed-responsive"><iframe src="https://player.vimeo.com/video/${match[1]}" frameborder="0" allowfullscreen></iframe></div>` : null;
  };
  const videoEmbed = (url) => {
    var _a;
    return (_a = youtubeEmbed(url)) != null ? _a : vimeoEmbed(url);
  };
  const inline = (text) => {
    text = text.replace(/!\[([^\]]*)\]\((https?:\/\/(?:www\.)?(?:youtube\.com\/watch\S+|youtu\.be\/\S+|vimeo\.com\/\S+))\)/gi, (_m, _alt, url) => {
      var _a;
      return (_a = videoEmbed(url)) != null ? _a : _m;
    });
    text = text.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1">');
    text = text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
    text = text.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_m, target, alias) => alias ? alias : target);
    text = text.replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>");
    text = text.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    text = text.replace(/__(.+?)__/g, "<strong>$1</strong>");
    text = text.replace(/\*(.+?)\*/g, "<em>$1</em>");
    text = text.replace(/_(.+?)_/g, "<em>$1</em>");
    text = text.replace(/`([^`]+)`/g, "<code>$1</code>");
    text = text.replace(/~~(.+?)~~/g, "<del>$1</del>");
    return text;
  };
  for (const rawLine of lines) {
    const line = rawLine.trimEnd();
    if (line.startsWith("```")) {
      if (!inCodeBlock) {
        closeLists();
        inCodeBlock = true;
        codeLang = line.slice(3).trim();
        codeBuffer = [];
      } else {
        inCodeBlock = false;
        htmlLines.push(`<pre><code class="language-${codeLang}">${escapeHtml(codeBuffer.join("\n"))}</code></pre>`);
      }
      continue;
    }
    if (inCodeBlock) {
      codeBuffer.push(rawLine);
      continue;
    }
    const trimmed = line.trim();
    if (!trimmed) {
      closeLists();
      htmlLines.push("");
      continue;
    }
    const embed = videoEmbed(trimmed);
    if (embed) {
      closeLists();
      htmlLines.push(embed);
      continue;
    }
    if (/^(?:---|\*\*\*|___)\s*$/.test(trimmed)) {
      closeLists();
      htmlLines.push("<hr>");
      continue;
    }
    const heading = line.match(/^(#{1,6})\s+(.+)$/);
    if (heading) {
      closeLists();
      const level = heading[1].length;
      htmlLines.push(`<h${level}>${inline(heading[2])}</h${level}>`);
      continue;
    }
    const quote = line.match(/^>\s(.+)$/);
    if (quote) {
      closeLists();
      htmlLines.push(`<blockquote>${inline(quote[1])}</blockquote>`);
      continue;
    }
    const ul = line.match(/^[-*+]\s(.+)$/);
    if (ul) {
      if (inOl) {
        htmlLines.push("</ol>");
        inOl = false;
      }
      if (!inUl) {
        htmlLines.push("<ul>");
        inUl = true;
      }
      htmlLines.push(`<li>${inline(ul[1])}</li>`);
      continue;
    }
    const ol = line.match(/^\d+\.\s(.+)$/);
    if (ol) {
      if (inUl) {
        htmlLines.push("</ul>");
        inUl = false;
      }
      if (!inOl) {
        htmlLines.push("<ol>");
        inOl = true;
      }
      htmlLines.push(`<li>${inline(ol[1])}</li>`);
      continue;
    }
    closeLists();
    htmlLines.push(`<p>${inline(trimmed)}</p>`);
  }
  if (inCodeBlock) htmlLines.push(`<pre><code class="language-${codeLang}">${escapeHtml(codeBuffer.join("\n"))}</code></pre>`);
  closeLists();
  return htmlLines.join("\n").trim();
}
function parseFrontmatter(content) {
  const result = {};
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return result;
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim().replace(/^["']|["']$/g, "");
    if (key) result[key] = value;
  }
  return result;
}
function stripFrontmatter(content) {
  return content.replace(/^---\n[\s\S]*?\n---\n?/, "");
}
async function setFrontmatterKey(app, file, key, value) {
  let content = await app.vault.read(file);
  const originalContent = content;
  const hasFM = /^---\n/.test(content);
  if (hasFM) {
    const fmEnd = content.indexOf("\n---", 4);
    if (fmEnd === -1) return;
    const fmBlock = content.slice(0, fmEnd);
    const rest = content.slice(fmEnd);
    const keyRegex = new RegExp(`^${key}:[\\t ]*(.*)$`, "m");
    if (keyRegex.test(fmBlock)) {
      content = fmBlock.replace(keyRegex, () => `${key}: ${value}`) + rest;
    } else {
      content = fmBlock + `
${key}: ${value}` + rest;
    }
  } else {
    content = `---
${key}: ${value}
---
${content}`;
  }
  if (content !== originalContent) await app.vault.modify(file, content);
}
function basicAuth(u, p) {
  return "Basic " + btoa(`${u}:${p}`);
}
async function wpRequest(s, method, endpoint, body) {
  const url = `${s.wpUrl.replace(/\/$/, "")}/wp-json/wp/v2/${endpoint}`;
  const resp = await (0, import_obsidian.requestUrl)({
    url,
    method,
    headers: {
      Authorization: basicAuth(s.wpUsername, s.wpPassword),
      "Content-Type": "application/json"
    },
    body: body ? JSON.stringify(body) : void 0,
    throw: false
  });
  if (resp.status >= 400) {
    let msg = `HTTP ${resp.status}`;
    try {
      const e = resp.json;
      if (e == null ? void 0 : e.message) msg = e.message;
      else if (e == null ? void 0 : e.code) msg = e.code;
    } catch (e) {
    }
    throw new Error(msg);
  }
  return resp.json;
}
async function resolveCategory(s, name) {
  const base = s.wpUrl.replace(/\/$/, "");
  const sr = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/categories?search=${encodeURIComponent(name)}&per_page=10`,
    method: "GET",
    headers: { Authorization: basicAuth(s.wpUsername, s.wpPassword) },
    throw: false
  });
  if (sr.status === 200) {
    const cats = sr.json;
    const match = cats.find((c) => c.name.toLowerCase() === name.toLowerCase());
    if (match) return match.id;
  }
  const cr = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/categories`,
    method: "POST",
    headers: { Authorization: basicAuth(s.wpUsername, s.wpPassword), "Content-Type": "application/json" },
    body: JSON.stringify({ name }),
    throw: false
  });
  if (cr.status >= 400) throw new Error(`Could not create category "${name}"`);
  return cr.json.id;
}
function categoryNamesFromFrontmatter(fm) {
  const raw = (fm["category"] || fm["categories"] || "").trim();
  if (!raw) return [];
  return raw.split(",").map((c) => c.trim()).filter(Boolean);
}
async function resolveCategories(s, fm) {
  const names = categoryNamesFromFrontmatter(fm);
  if (names.length === 0) return void 0;
  const ids = [];
  for (const name of names) ids.push(await resolveCategory(s, name));
  return ids;
}
async function findExistingPostByTitle(s, title) {
  var _a;
  const base = s.wpUrl.replace(/\/$/, "");
  const resp = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/posts?search=${encodeURIComponent(title)}&per_page=10&status=any`,
    method: "GET",
    headers: { Authorization: basicAuth(s.wpUsername, s.wpPassword) },
    throw: false
  });
  if (resp.status >= 400) return null;
  const posts = resp.json;
  const match = posts.find((p) => {
    var _a2, _b;
    return ((_b = (_a2 = p.title) == null ? void 0 : _a2.rendered) != null ? _b : "").replace(/<[^>]+>/g, "").trim().toLowerCase() === title.trim().toLowerCase();
  });
  return (_a = match == null ? void 0 : match.id) != null ? _a : null;
}
async function uploadImage(s, app, filePath) {
  var _a;
  const base = s.wpUrl.replace(/\/$/, "");
  const file = app.vault.getAbstractFileByPath(filePath);
  if (!(file instanceof import_obsidian.TFile)) throw new Error(`Image not found: ${filePath}`);
  const binary = await app.vault.readBinary(file);
  const ext = file.extension.toLowerCase();
  const mimeMap = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    gif: "image/gif",
    webp: "image/webp",
    svg: "image/svg+xml"
  };
  const mime = (_a = mimeMap[ext]) != null ? _a : "application/octet-stream";
  const res = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/media`,
    method: "POST",
    headers: {
      Authorization: basicAuth(s.wpUsername, s.wpPassword),
      "Content-Type": mime,
      "Content-Disposition": `attachment; filename="${file.name}"`
    },
    body: binary,
    throw: false
  });
  if (res.status >= 400) throw new Error(`Image upload failed for ${file.name}`);
  return res.json.source_url;
}
async function processImages(app, s, html, sourceFile) {
  const matches = [...html.matchAll(/src="([^"]+)"/g)];
  for (const match of matches) {
    const src = match[1];
    if (/^https?:\/\//.test(src)) continue;
    const resolved = (0, import_obsidian.normalizePath)(sourceFile.parent ? `${sourceFile.parent.path}/${src}` : src);
    try {
      html = html.replace(`src="${src}"`, `src="${await uploadImage(s, app, resolved)}"`);
    } catch (e) {
    }
  }
  const wikiMatches = [...html.matchAll(/!\[\[([^\]]+\.(png|jpe?g|gif|webp|svg))\]\]/gi)];
  for (const match of wikiMatches) {
    const fileName = match[1];
    const found = app.vault.getFiles().find((f) => f.name === fileName || f.path === fileName);
    if (!found) continue;
    try {
      const remoteUrl = await uploadImage(s, app, found.path);
      html = html.replace(match[0], `<img src="${remoteUrl}" alt="${fileName}">`);
    } catch (e) {
    }
  }
  return html;
}
var FolderSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  getItems() {
    const folders = [];
    const recurse = (folder) => {
      folders.push(folder);
      for (const child of folder.children) {
        if (child instanceof import_obsidian.TFolder) recurse(child);
      }
    };
    recurse(this.app.vault.getRoot());
    return folders;
  }
  getItemText(folder) {
    return folder.path === "/" ? "(Vault root)" : folder.path;
  }
  onChooseItem(folder) {
    this.onChoose(folder);
  }
};
var FileSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};
var NewNoteModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "New note from WP template" });
    const wrap = contentEl.createDiv();
    wrap.createEl("label", { text: "Note name:" });
    this.inputEl = wrap.createEl("input", { type: "text", placeholder: "My new post" });
    this.inputEl.style.cssText = "width:100%;margin-top:8px;padding:6px;font-size:14px;";
    const btns = contentEl.createDiv();
    btns.style.cssText = "display:flex;gap:8px;margin-top:16px;justify-content:flex-end;";
    btns.createEl("button", { text: "Cancel" }).onclick = () => this.close();
    const ok = btns.createEl("button", { text: "Create note", cls: "mod-cta" });
    ok.onclick = () => {
      this.onSubmit(this.inputEl.value);
      this.close();
    };
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        this.onSubmit(this.inputEl.value);
        this.close();
      }
    });
    this.inputEl.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var WPPublisherPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("upload-cloud", "Publish to WordPress", () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view == null ? void 0 : view.file) this.publishNote(view.file, "publish");
      else new import_obsidian.Notice("Open a note first.");
    });
    this.addCommand({
      id: "wp-publish",
      name: "Publish note to WordPress",
      editorCallback: (_e, view) => {
        if (view.file) this.publishNote(view.file, "publish");
      }
    });
    this.addCommand({
      id: "wp-draft",
      name: "Save note as WordPress draft",
      editorCallback: (_e, view) => {
        if (view.file) this.publishNote(view.file, "draft");
      }
    });
    this.addCommand({
      id: "wp-revert-draft",
      name: "Revert WordPress post to draft",
      editorCallback: (_e, view) => {
        if (view.file) this.revertToDraft(view.file);
      }
    });
    this.addCommand({
      id: "wp-new-from-template",
      name: "New note from WP Publisher template",
      callback: () => this.newNoteFromTemplate()
    });
    this.addCommand({
      id: "wp-apply-template",
      name: "Apply WP Publisher template to current note",
      editorCallback: (_e, view) => {
        if (view.file) this.applyTemplateToCurrentNote(view.file);
      }
    });
    this.registerSavedHotkeys();
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (!this.settings.syncOnSave) return;
        if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") return;
        const content = await this.app.vault.read(file);
        const fm = parseFrontmatter(content);
        if (fm["wp-id"]) await this.syncStatus(file, fm["wp-id"]);
      })
    );
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") return;
        await this.autoApplyTemplateToNewNote(file);
      })
    );
    this.addSettingTab(new WPPublisherSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ── Hotkeys registered from stored combos ──
  registerSavedHotkeys() {
    const tryHotkey = (hk, action) => {
      if (!hk) return;
      const modMap = {
        Ctrl: "Mod",
        Alt: "Alt",
        Shift: "Shift",
        Meta: "Meta"
      };
      const handler = (e) => {
        const pressed = eventToHotkey(e);
        if (!pressed) return;
        if (pressed.key === hk.key && pressed.modifiers.length === hk.modifiers.length && hk.modifiers.every((m) => pressed.modifiers.includes(m))) {
          e.preventDefault();
          action();
        }
      };
      this.registerDomEvent(document, "keydown", handler);
    };
    tryHotkey(this.settings.hotkeyPublish, () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view == null ? void 0 : view.file) this.publishNote(view.file, "publish");
    });
    tryHotkey(this.settings.hotkeyDraft, () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view == null ? void 0 : view.file) this.publishNote(view.file, "draft");
    });
  }
  // ── Validate settings ──
  validateSettings() {
    if (!this.settings.wpUrl) return "WordPress URL is not set. Go to Settings \u2192 WP Publisher.";
    if (!this.settings.wpUsername) return "WordPress username is not set.";
    if (!this.settings.wpPassword) return "WordPress application password is not set.";
    try {
      new URL(this.settings.wpUrl);
    } catch (e) {
      return "WordPress URL is invalid \u2014 include https://, e.g. https://mysite.com";
    }
    return null;
  }
  // ── Folder check ──
  fileIsAllowed(file) {
    var _a;
    const folder = this.settings.publishFolder.trim();
    if (!folder || folder === "/") return true;
    return file.path.startsWith(folder + "/") || ((_a = file.parent) == null ? void 0 : _a.path) === folder;
  }
  // ── Publish / update ──
  async publishNote(file, desiredStatus) {
    const err = this.validateSettings();
    if (err) {
      new import_obsidian.Notice(`\u26D4 ${err}`, 8e3);
      return;
    }
    if (!this.fileIsAllowed(file)) {
      const folder = this.settings.publishFolder;
      new import_obsidian.Notice(`\u26D4 This note is not in the publish folder:
"${folder}"

Change the folder in Settings \u2192 WP Publisher, or move the note.`, 1e4);
      return;
    }
    const content = await this.app.vault.read(file);
    const fm = parseFrontmatter(content);
    let html = mdToHtml(stripFrontmatter(content));
    try {
      html = await processImages(this.app, this.settings, html, file);
    } catch (e) {
    }
    const title = fm["title"] || file.basename;
    const payload = {
      title,
      content: html,
      status: desiredStatus,
      excerpt: fm["excerpt"] || ""
    };
    const previousStatus = (fm["status"] || "").trim().toLowerCase();
    try {
      const categoryIds = await resolveCategories(this.settings, fm);
      if (categoryIds) payload["categories"] = categoryIds;
      const existingId = fm["wp-id"] || await findExistingPostByTitle(this.settings, title);
      let post;
      if (existingId) {
        post = await wpRequest(this.settings, "POST", `posts/${existingId}`, payload);
        await setFrontmatterKey(this.app, file, "wp-id", String(post.id));
        const msg = desiredStatus === "draft" ? previousStatus === "publish" ? "Taken down to draft" : "Draft updated" : previousStatus === "draft" ? "Published from draft" : "Post updated";
        new import_obsidian.Notice(`\u2705 ${msg}: "${title}"`);
      } else {
        post = await wpRequest(this.settings, "POST", "posts", payload);
        await setFrontmatterKey(this.app, file, "wp-id", String(post.id));
        new import_obsidian.Notice(desiredStatus === "publish" ? `\u2705 Published: "${title}"` : `\u2705 Saved as new draft: "${title}"`);
      }
      await setFrontmatterKey(this.app, file, "status", post.status);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      await setFrontmatterKey(this.app, file, "status", "error");
      new import_obsidian.Notice(`\u26D4 Publish failed: ${msg}`, 1e4);
    }
  }
  // ── Revert to draft ──
  async revertToDraft(file) {
    const err = this.validateSettings();
    if (err) {
      new import_obsidian.Notice(`\u26D4 ${err}`, 8e3);
      return;
    }
    const content = await this.app.vault.read(file);
    const fm = parseFrontmatter(content);
    if (!fm["wp-id"]) {
      new import_obsidian.Notice("\u26D4 This note hasn't been published yet (no wp-id).");
      return;
    }
    try {
      await wpRequest(this.settings, "POST", `posts/${fm["wp-id"]}`, { status: "draft" });
      await setFrontmatterKey(this.app, file, "status", "draft");
      new import_obsidian.Notice(`\u2705 Reverted to draft: "${fm["title"] || file.basename}"`);
    } catch (e) {
      new import_obsidian.Notice(`\u26D4 Revert failed: ${e instanceof Error ? e.message : String(e)}`, 1e4);
    }
  }
  // ── Sync on save ──
  async syncStatus(file, wpId) {
    try {
      const post = await wpRequest(this.settings, "GET", `posts/${wpId}`);
      await setFrontmatterKey(this.app, file, "status", post.status);
    } catch (e) {
    }
  }
  // ── Template helpers ──
  async getTemplateContent() {
    const templatePath = this.settings.defaultTemplatePath.trim();
    if (!templatePath) return DEFAULT_WP_POST_TEMPLATE;
    const templateFile = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(templatePath));
    if (!(templateFile instanceof import_obsidian.TFile)) {
      throw new Error(`Template note not found: "${templatePath}". Check the path in Settings \u2192 WP Publisher.`);
    }
    return await this.app.vault.read(templateFile);
  }
  // ── New note from template ──
  async newNoteFromTemplate() {
    let templateContent;
    try {
      templateContent = await this.getTemplateContent();
    } catch (e) {
      new import_obsidian.Notice(`\u26D4 ${e instanceof Error ? e.message : String(e)}`, 1e4);
      return;
    }
    new NewNoteModal(this.app, async (noteName) => {
      if (!noteName.trim()) {
        new import_obsidian.Notice("Note name cannot be empty.");
        return;
      }
      const folder = this.settings.publishFolder.trim();
      const fileName = noteName.endsWith(".md") ? noteName : `${noteName}.md`;
      const newPath = (0, import_obsidian.normalizePath)(folder && folder !== "/" ? `${folder}/${fileName}` : fileName);
      try {
        const newFile = await this.app.vault.create(newPath, templateContent);
        await this.app.workspace.getLeaf(false).openFile(newFile);
        new import_obsidian.Notice(`\u2705 Created "${noteName}" from template.`);
      } catch (e) {
        new import_obsidian.Notice(`\u26D4 Could not create note: ${e instanceof Error ? e.message : String(e)}`, 8e3);
      }
    }).open();
  }
  async applyTemplateToCurrentNote(file) {
    try {
      const existing = await this.app.vault.read(file);
      if (existing.trim().length > 0 && !confirm("This note already has content. Add the WP template to the top anyway?")) return;
      const templateContent = await this.getTemplateContent();
      await this.app.vault.modify(file, `${templateContent.trim()}

${existing}`.trimEnd() + "\n");
      new import_obsidian.Notice(`\u2705 WP Publisher template applied to "${file.basename}".`);
    } catch (e) {
      new import_obsidian.Notice(`\u26D4 Could not apply template: ${e instanceof Error ? e.message : String(e)}`, 1e4);
    }
  }
  async autoApplyTemplateToNewNote(file) {
    if (!this.settings.autoApplyTemplateOnNewNotes) return;
    const folder = this.settings.publishFolder.trim();
    if (!folder || folder === "/") return;
    if (!this.fileIsAllowed(file)) return;
    const templatePath = this.settings.defaultTemplatePath.trim();
    if (templatePath && (0, import_obsidian.normalizePath)(templatePath) === file.path) return;
    try {
      await wait(250);
      const existing = await this.app.vault.read(file);
      if (existing.trim().length > 0) return;
      const templateContent = await this.getTemplateContent();
      await this.app.vault.modify(file, templateContent.trimEnd() + "\n");
      new import_obsidian.Notice(`\u2705 WP template applied to new post note: "${file.basename}".`);
    } catch (e) {
      new import_obsidian.Notice(`\u26D4 Could not auto-apply WP template: ${e instanceof Error ? e.message : String(e)}`, 1e4);
    }
  }
};
var WPPublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: `WordPress connection \u2014 Hermes ${HERMES_PLUGIN_VERSION}` });
    new import_obsidian.Setting(containerEl).setName("Site URL").setDesc("Full URL including https://, e.g. https://mysite.com").addText(
      (t) => t.setPlaceholder("https://mysite.com").setValue(this.plugin.settings.wpUrl).onChange(async (v) => {
        this.plugin.settings.wpUrl = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Username").setDesc("Your WordPress login username").addText(
      (t) => t.setPlaceholder("admin").setValue(this.plugin.settings.wpUsername).onChange(async (v) => {
        this.plugin.settings.wpUsername = v.trim();
        await this.plugin.saveSettings();
      })
    );
    const passwordIsLocked = this.plugin.settings.wpPassword.trim().length > 0;
    let pendingPassword = "";
    let passwordInputEl = null;
    const passwordSetting = new import_obsidian.Setting(containerEl).setName("Application password").setDesc(passwordIsLocked ? "Saved and locked. The password is not shown here again. Clear it before entering a replacement." : "Paste the one-time WordPress Application Password, then click Lock password. Different from your login password.").addText((t) => {
      passwordInputEl = t.inputEl;
      t.setPlaceholder(passwordIsLocked ? "Password saved and locked" : "xxxx xxxx xxxx xxxx xxxx xxxx").setValue("").onChange((v) => {
        pendingPassword = v.trim();
      });
      t.inputEl.type = "password";
      t.inputEl.disabled = passwordIsLocked;
      t.inputEl.autocomplete = "new-password";
    }).addButton(
      (btn) => btn.setButtonText("?").setTooltip("What is this?").onClick(() => {
        new import_obsidian.Notice("Use a WordPress Application Password. Paste it once, click Lock password, and the plugin hides it. To change it later, click Clear password and paste a new one.", 12e3);
      })
    );
    if (!passwordIsLocked) {
      passwordSetting.addButton(
        (btn) => btn.setButtonText("Show").setTooltip("Temporarily show/hide what you typed before locking").onClick(() => {
          if (!passwordInputEl) return;
          const showing = passwordInputEl.type === "text";
          passwordInputEl.type = showing ? "password" : "text";
          btn.setButtonText(showing ? "Show" : "Hide");
        })
      ).addButton(
        (btn) => btn.setButtonText("Lock password").setCta().onClick(async () => {
          if (!pendingPassword) {
            new import_obsidian.Notice("Paste the WordPress application password first, then click Lock password.", 8e3);
            return;
          }
          this.plugin.settings.wpPassword = pendingPassword;
          await this.plugin.saveSettings();
          pendingPassword = "";
          new import_obsidian.Notice("\u2705 Application password saved and locked. It will not be shown in settings again.", 8e3);
          this.display();
        })
      );
    } else {
      passwordSetting.addButton(
        (btn) => btn.setButtonText("Clear password").setWarning().onClick(async () => {
          this.plugin.settings.wpPassword = "";
          await this.plugin.saveSettings();
          new import_obsidian.Notice("Application password cleared. Paste a new one and click Lock password to replace it.", 8e3);
          this.display();
        })
      );
    }
    const testRow = containerEl.createDiv();
    testRow.style.marginBottom = "16px";
    const testBtn = testRow.createEl("button", { text: "Test connection", cls: "mod-cta" });
    const testResult = testRow.createEl("span");
    testResult.style.cssText = "margin-left:12px;font-size:13px;";
    testBtn.onclick = async () => {
      testResult.textContent = "Testing\u2026";
      const validErr = this.plugin.validateSettings();
      if (validErr) {
        testResult.textContent = `\u26D4 ${validErr}`;
        return;
      }
      try {
        await wpRequest(this.plugin.settings, "GET", "posts?per_page=1");
        testResult.textContent = "\u2705 Connected!";
      } catch (e) {
        testResult.textContent = `\u26D4 ${e instanceof Error ? e.message : String(e)}`;
      }
    };
    containerEl.createEl("h2", { text: "Publishing rules" });
    const folderSetting = new import_obsidian.Setting(containerEl).setName("Publish folder").setDesc("Only notes in this folder can be published. Leave empty to allow any note.").addText((t) => {
      t.setPlaceholder("(any folder)").setValue(this.plugin.settings.publishFolder).onChange(async (v) => {
        var _a;
        this.plugin.settings.publishFolder = v.trim();
        await this.plugin.saveSettings();
        (_a = folderSetting.settingEl.querySelector(".wp-folder-label")) == null ? void 0 : _a.remove();
      });
      return t;
    }).addButton(
      (btn) => btn.setButtonText("Browse\u2026").onClick(() => {
        new FolderSuggestModal(this.app, async (folder) => {
          const path = folder.path === "/" ? "" : folder.path;
          this.plugin.settings.publishFolder = path;
          await this.plugin.saveSettings();
          this.display();
        }).open();
      })
    );
    if (this.plugin.settings.publishFolder) {
      const badge = folderSetting.settingEl.createEl("div", {
        cls: "wp-folder-label",
        text: `\u{1F4C1} ${this.plugin.settings.publishFolder}`
      });
      badge.style.cssText = "font-size:12px;color:var(--text-muted);margin-top:4px;";
    }
    if (this.plugin.settings.publishFolder) {
      new import_obsidian.Setting(containerEl).setName("").addButton(
        (btn) => btn.setButtonText("Clear folder restriction (allow all notes)").onClick(async () => {
          this.plugin.settings.publishFolder = "";
          await this.plugin.saveSettings();
          this.display();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Sync status on save").setDesc("Silently update status: in frontmatter whenever you save a note that has a wp-id.").addToggle(
      (t) => t.setValue(this.plugin.settings.syncOnSave).onChange(async (v) => {
        this.plugin.settings.syncOnSave = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Template" });
    const tplSetting = new import_obsidian.Setting(containerEl).setName("Default template note").setDesc("Path to a note used as the template for new posts. Leave blank to use the built-in Hermes template. The note filename is used as the WordPress title.").addText((t) => {
      t.setPlaceholder("Templates/WP Post.md").setValue(this.plugin.settings.defaultTemplatePath).onChange(async (v) => {
        this.plugin.settings.defaultTemplatePath = v.trim();
        await this.plugin.saveSettings();
        this.refreshTemplateStatus(tplSetting.settingEl);
      });
      return t;
    }).addButton(
      (btn) => btn.setButtonText("Browse\u2026").onClick(() => {
        new FileSuggestModal(this.app, async (file) => {
          this.plugin.settings.defaultTemplatePath = file.path;
          await this.plugin.saveSettings();
          this.display();
        }).open();
      })
    );
    this.refreshTemplateStatus(tplSetting.settingEl);
    new import_obsidian.Setting(containerEl).setName("Apply template to new notes in publish folder").setDesc("When enabled, ordinary blank notes created inside the publish folder automatically receive the selected WP template. Existing/non-empty notes are left alone.").addToggle(
      (t) => t.setValue(this.plugin.settings.autoApplyTemplateOnNewNotes).onChange(async (v) => {
        this.plugin.settings.autoApplyTemplateOnNewNotes = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Hotkeys" });
    containerEl.createEl("p", {
      text: "Click a record button, then press your desired key combination (must include Ctrl, Alt, Shift, or Meta). Press Escape to cancel recording."
    }).style.cssText = "font-size:13px;color:var(--text-muted);margin-bottom:12px;";
    this.addHotkeySetting(containerEl, "Publish hotkey", "hotkeyPublish");
    this.addHotkeySetting(containerEl, "Draft hotkey", "hotkeyDraft");
    containerEl.createEl("p", {
      text: "You can also assign hotkeys via Obsidian's built-in Settings \u2192 Hotkeys page \u2014 search for 'WP Publisher' to find all commands there."
    }).style.cssText = "font-size:12px;color:var(--text-muted);margin-top:8px;";
    containerEl.createEl("h2", { text: "Frontmatter keys" });
    const info = containerEl.createEl("div");
    info.style.cssText = "font-size:13px;color:var(--text-muted);line-height:1.8;";
    info.innerHTML = `
			<code>title:</code> \u2014 optional override; by default the post title comes from the note filename<br>
			<code>category:</code> \u2014 WordPress category (auto-created if new; blank uses WordPress Uncategorized)<br>
			<code>excerpt:</code> \u2014 post summary / meta description<br>
			<code>status:</code> \u2014 updated automatically by the plugin<br>
			<code>wp-id:</code> \u2014 written automatically after first publish<br>
		`;
  }
  // Show a green ✅ or red ⛔ next to the template path
  refreshTemplateStatus(settingEl) {
    var _a;
    (_a = settingEl.querySelector(".wp-tpl-status")) == null ? void 0 : _a.remove();
    const path = this.plugin.settings.defaultTemplatePath.trim();
    if (!path) return;
    const exists = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(path)) instanceof import_obsidian.TFile;
    const span = settingEl.createEl("span", {
      cls: "wp-tpl-status",
      text: exists ? "\u2705 Found" : "\u26D4 Not found \u2014 check the path"
    });
    span.style.cssText = `font-size:12px;margin-left:8px;color:${exists ? "var(--color-green)" : "var(--color-red)"};`;
  }
  // Build a single hotkey recorder row
  addHotkeySetting(container, label, settingKey) {
    const current = this.plugin.settings[settingKey];
    const row = new import_obsidian.Setting(container).setName(label);
    const display = row.controlEl.createEl("span");
    display.style.cssText = "min-width:160px;display:inline-block;font-size:13px;padding:4px 8px;background:var(--background-modifier-form-field);border-radius:4px;border:1px solid var(--background-modifier-border);";
    display.textContent = hotkeyLabel(current);
    let recording = false;
    let keydownHandler = null;
    const stopRecording = () => {
      recording = false;
      recordBtn.textContent = "Record";
      recordBtn.classList.remove("mod-warning");
      if (keydownHandler) {
        document.removeEventListener("keydown", keydownHandler, true);
        keydownHandler = null;
      }
    };
    const recordBtn = row.controlEl.createEl("button", { text: "Record" });
    recordBtn.style.marginLeft = "8px";
    recordBtn.onclick = () => {
      if (recording) {
        stopRecording();
        return;
      }
      recording = true;
      recordBtn.textContent = "Press keys\u2026 (Esc to cancel)";
      recordBtn.classList.add("mod-warning");
      keydownHandler = (e) => {
        e.preventDefault();
        e.stopPropagation();
        if (e.key === "Escape") {
          stopRecording();
          return;
        }
        const hk = eventToHotkey(e);
        if (!hk) return;
        stopRecording();
        this.plugin.settings[settingKey] = hk;
        this.plugin.saveSettings();
        display.textContent = hotkeyLabel(hk);
        new import_obsidian.Notice(`\u2705 ${label} set to ${hotkeyLabel(hk)}
Restart Obsidian to remove any old binding.`);
      };
      document.addEventListener("keydown", keydownHandler, true);
    };
    const clearBtn = row.controlEl.createEl("button", { text: "Clear" });
    clearBtn.style.marginLeft = "6px";
    clearBtn.onclick = async () => {
      stopRecording();
      this.plugin.settings[settingKey] = null;
      await this.plugin.saveSettings();
      display.textContent = hotkeyLabel(null);
    };
  }
};
