/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WPPublisherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  wpUrl: "",
  wpUsername: "",
  wpPassword: "",
  showSidebarButton: true,
  defaultTemplatePath: "",
  publishFolder: "",
  wpCategories: "Blog\nNews\nProjects\nTo Do List\nUncategorized\nWrite Ups",
  autoCreateCategories: true,
  wpCategoriesLastRefreshedAt: 0,
  wpCategoriesLastSource: "manual",
  wpCategoriesLastWordPressSnapshot: "",
  wpCategoriesLastMessage: "",
  wpIdCache: {},
  wpContentHashCache: {},
  wpSyncMigrationVersion: 0,
  autoApplyTemplateOnNewNotes: true,
  syncOnSave: true,
  hotkeyPublish: null,
  hotkeyDraft: null
};
var WP_PUBLISHER_VERSION = "1.0.4";
var DEFAULT_WP_POST_TEMPLATE = `---
category: 
excerpt: 
status: draft
comments: off
wp-id: 
wp-sync: 
---
`;
function categoryNamesFromSettings(s) {
  return s.wpCategories.split(/[\n,]/).map((c) => c.trim()).filter(Boolean);
}
function canonicalCategoryName(s, name) {
  const match = categoryNamesFromSettings(s).find((c) => c.toLowerCase() === name.toLowerCase());
  return match || name;
}
function unknownCategoryNames(s, names) {
  const known = categoryNamesFromSettings(s).map((c) => c.toLowerCase());
  return names.filter((name) => !known.includes(name.toLowerCase()));
}
function mergeCategoryNames(existing, incoming) {
  return Array.from(new Map([...existing, ...incoming].map((c) => c.trim()).filter(Boolean).map((c) => [c.toLowerCase(), c])).values()).sort((a, b) => a.localeCompare(b));
}
function normalizedCategorySnapshot(value) {
  const categories = Array.isArray(value) ? value : value.split(/[\n,]/);
  return mergeCategoryNames([], categories).join("\n");
}
function formatRelativeRefreshTime(timestamp) {
  if (!timestamp) return "never";
  const diffMs = Math.max(0, Date.now() - timestamp);
  const diffMinutes = Math.floor(diffMs / 6e4);
  if (diffMinutes < 1) return "just now";
  if (diffMinutes === 1) return "1 minute ago";
  if (diffMinutes < 60) return `${diffMinutes} minutes ago`;
  const diffHours = Math.floor(diffMinutes / 60);
  if (diffHours === 1) return "1 hour ago";
  if (diffHours < 24) return `${diffHours} hours ago`;
  const diffDays = Math.floor(diffHours / 24);
  if (diffDays === 1) return "1 day ago";
  return `${diffDays} days ago`;
}
function yamlQuote(value) {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
function buildDefaultTemplate(s) {
  const categories = categoryNamesFromSettings(s);
  const categoryReference = categories.length ? `%% Categories: ${categories.join(" \xB7 ")} %%

` : "";
  return `${DEFAULT_WP_POST_TEMPLATE}${categoryReference}%%
Ctrl + Alt + D = Draft
Ctrl + Shift + P = Publish
%%
`;
}
var wait = (ms) => new Promise((resolve) => window.setTimeout(resolve, ms));
async function flushPendingObsidianPropertyEdit() {
  const active = document.activeElement;
  if (active instanceof HTMLElement) {
    active.dispatchEvent(new Event("input", { bubbles: true }));
    active.dispatchEvent(new Event("change", { bubbles: true }));
    active.blur();
    await wait(250);
  }
}
function hotkeyLabel(hk) {
  if (!hk) return "Not set";
  const parts = [...hk.modifiers, hk.key];
  return parts.join(" + ");
}
function eventToHotkey(e) {
  if (["Control", "Shift", "Alt", "Meta"].includes(e.key)) return null;
  const modifiers = [];
  if (e.ctrlKey) modifiers.push("Ctrl");
  if (e.altKey) modifiers.push("Alt");
  if (e.shiftKey) modifiers.push("Shift");
  if (e.metaKey) modifiers.push("Meta");
  if (modifiers.length === 0) return null;
  const key = e.key.length === 1 ? e.key.toUpperCase() : e.key;
  return { modifiers, key };
}
function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function mdToHtml(md) {
  md = md.replace(/%%[\s\S]*?%%/g, "").trim();
  const lines = md.split("\n");
  const htmlLines = [];
  let inUl = false;
  let inOl = false;
  let inCodeBlock = false;
  let codeLang = "";
  let codeBuffer = [];
  const closeLists = () => {
    if (inUl) {
      htmlLines.push("</ul>");
      inUl = false;
    }
    if (inOl) {
      htmlLines.push("</ol>");
      inOl = false;
    }
  };
  const youtubeEmbed = (url) => {
    const match = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([A-Za-z0-9_-]+)/);
    return match ? `<div class="wp-embed-responsive"><iframe src="https://www.youtube.com/embed/${match[1]}" frameborder="0" allowfullscreen></iframe></div>` : null;
  };
  const vimeoEmbed = (url) => {
    const match = url.match(/vimeo\.com\/(\d+)/);
    return match ? `<div class="wp-embed-responsive"><iframe src="https://player.vimeo.com/video/${match[1]}" frameborder="0" allowfullscreen></iframe></div>` : null;
  };
  const videoEmbed = (url) => {
    var _a;
    return (_a = youtubeEmbed(url)) != null ? _a : vimeoEmbed(url);
  };
  const inline = (text) => {
    text = text.replace(/!\[([^\]]*)\]\((https?:\/\/(?:www\.)?(?:youtube\.com\/watch\S+|youtu\.be\/\S+|vimeo\.com\/\S+))\)/gi, (_m, _alt, url) => {
      var _a;
      return (_a = videoEmbed(url)) != null ? _a : _m;
    });
    text = text.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1">');
    text = text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
    text = text.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_m, target, alias) => alias ? alias : target);
    text = text.replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>");
    text = text.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    text = text.replace(/__(.+?)__/g, "<strong>$1</strong>");
    text = text.replace(/\*(.+?)\*/g, "<em>$1</em>");
    text = text.replace(/_(.+?)_/g, "<em>$1</em>");
    text = text.replace(/`([^`]+)`/g, "<code>$1</code>");
    text = text.replace(/~~(.+?)~~/g, "<del>$1</del>");
    return text;
  };
  for (const rawLine of lines) {
    const line = rawLine.trimEnd();
    if (line.startsWith("```")) {
      if (!inCodeBlock) {
        closeLists();
        inCodeBlock = true;
        codeLang = line.slice(3).trim();
        codeBuffer = [];
      } else {
        inCodeBlock = false;
        htmlLines.push(`<pre><code class="language-${codeLang}">${escapeHtml(codeBuffer.join("\n"))}</code></pre>`);
      }
      continue;
    }
    if (inCodeBlock) {
      codeBuffer.push(rawLine);
      continue;
    }
    const trimmed = line.trim();
    if (!trimmed) {
      closeLists();
      htmlLines.push("");
      continue;
    }
    const embed = videoEmbed(trimmed);
    if (embed) {
      closeLists();
      htmlLines.push(embed);
      continue;
    }
    if (/^(?:---|\*\*\*|___)\s*$/.test(trimmed)) {
      closeLists();
      htmlLines.push("<hr>");
      continue;
    }
    const heading = line.match(/^(#{1,6})\s+(.+)$/);
    if (heading) {
      closeLists();
      const level = heading[1].length;
      htmlLines.push(`<h${level}>${inline(heading[2])}</h${level}>`);
      continue;
    }
    const quote = line.match(/^>\s(.+)$/);
    if (quote) {
      closeLists();
      htmlLines.push(`<blockquote>${inline(quote[1])}</blockquote>`);
      continue;
    }
    const ul = line.match(/^[-*+]\s(.+)$/);
    if (ul) {
      if (inOl) {
        htmlLines.push("</ol>");
        inOl = false;
      }
      if (!inUl) {
        htmlLines.push("<ul>");
        inUl = true;
      }
      htmlLines.push(`<li>${inline(ul[1])}</li>`);
      continue;
    }
    const ol = line.match(/^\d+\.\s(.+)$/);
    if (ol) {
      if (inUl) {
        htmlLines.push("</ul>");
        inUl = false;
      }
      if (!inOl) {
        htmlLines.push("<ol>");
        inOl = true;
      }
      htmlLines.push(`<li>${inline(ol[1])}</li>`);
      continue;
    }
    closeLists();
    htmlLines.push(`<p>${inline(trimmed)}</p>`);
  }
  if (inCodeBlock) htmlLines.push(`<pre><code class="language-${codeLang}">${escapeHtml(codeBuffer.join("\n"))}</code></pre>`);
  closeLists();
  return htmlLines.join("\n").trim();
}
function parseFrontmatter(content) {
  const result = {};
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return result;
  let currentListKey = "";
  for (const line of match[1].split("\n")) {
    const listItem = line.match(/^\s*-\s+(.+)$/);
    if (listItem && currentListKey) {
      const value2 = listItem[1].trim().replace(/^["']|["']$/g, "");
      result[currentListKey] = result[currentListKey] ? `${result[currentListKey]}, ${value2}` : value2;
      continue;
    }
    const idx = line.indexOf(":");
    if (idx === -1) {
      currentListKey = "";
      continue;
    }
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim().replace(/^["']|["']$/g, "");
    currentListKey = key && !value ? key : "";
    if (/^\[.*\]$/.test(value)) {
      value = value.slice(1, -1).split(",").map((v) => v.trim().replace(/^["']|["']$/g, "")).filter(Boolean).join(", ");
    }
    if (key && value) result[key] = value;
  }
  return result;
}
function stripFrontmatter(content) {
  return content.replace(/^---\n[\s\S]*?\n---\n?/, "");
}
function stripPrivateComments(content) {
  return content.replace(/%%[\s\S]*?%%/g, "");
}
function hashString(value) {
  let hash = 5381;
  for (let i = 0; i < value.length; i++) {
    hash = (hash << 5) + hash ^ value.charCodeAt(i);
  }
  return (hash >>> 0).toString(16);
}
function postContentFingerprint(content) {
  const fm = parseFrontmatter(content);
  const body = stripPrivateComments(stripFrontmatter(content)).trim();
  const meaningfulFrontmatter = ["title", "category", "categories", "excerpt", "comments", "comment_status"].map((key) => `${key}:${(fm[key] || "").trim()}`).join("\n");
  return hashString(`${meaningfulFrontmatter}\n---\n${body}`);
}
function getCommentStatus(fm) {
  const raw = (fm["comments"] || fm["comment_status"] || "").trim().toLowerCase();
  if (!raw) return null;
  if (["on", "open", "enable", "enabled", "yes", "true", "allow", "allowed"].includes(raw)) return "open";
  if (["off", "closed", "close", "disable", "disabled", "no", "false", "deny", "denied"].includes(raw)) return "closed";
  return null;
}
async function setFrontmatterKey(app, file, key, value) {
  let content = await app.vault.read(file);
  const originalContent = content;
  const hasFM = /^---\n/.test(content);
  if (hasFM) {
    const fmEnd = content.indexOf("\n---", 4);
    if (fmEnd === -1) return;
    const fmBlock = content.slice(0, fmEnd);
    const rest = content.slice(fmEnd);
    const keyRegex = new RegExp(`^${key}:[\\t ]*(.*)$`, "m");
    if (keyRegex.test(fmBlock)) {
      content = fmBlock.replace(keyRegex, () => `${key}: ${value}`) + rest;
    } else {
      content = fmBlock + `
${key}: ${value}` + rest;
    }
  } else {
    content = `---
${key}: ${value}
---
${content}`;
  }
  if (content !== originalContent) await app.vault.modify(file, content);
}
async function deleteFrontmatterKey(app, file, key) {
  let content = await app.vault.read(file);
  const originalContent = content;
  const hasFM = /^---\n/.test(content);
  if (!hasFM) return;
  const fmEnd = content.indexOf("\n---", 4);
  if (fmEnd === -1) return;
  const fmBlock = content.slice(0, fmEnd);
  const rest = content.slice(fmEnd);
  const keyRegex = new RegExp(`^${key}:[\\t ]*.*(?:\\n|$)`, "m");
  if (!keyRegex.test(fmBlock)) return;
  const newFmBlock = fmBlock.replace(keyRegex, "").replace(/\n{3,}/g, "\n\n").replace(/\n$/, "");
  content = `${newFmBlock}${rest}`;
  if (content !== originalContent) await app.vault.modify(file, content);
}
function basicAuth(u, p) {
  return "Basic " + btoa(`${u}:${p}`);
}
function normalizeWpIdentity(value) {
  return value.trim().toLowerCase();
}
function wpUserMatchesConfiguredUsername(user, configuredUsername) {
  const expected = normalizeWpIdentity(configuredUsername);
  return [user.username, user.slug, user.name].filter(Boolean).some((value) => normalizeWpIdentity(String(value)) === expected);
}
async function testWordPressConnection(s) {
  const base = s.wpUrl.replace(/\/$/, "");
  const resp = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/users/me?context=edit`,
    method: "GET",
    headers: { Authorization: basicAuth(s.wpUsername, s.wpPassword) },
    throw: false
  });
  if (resp.status >= 400) {
    let msg = `HTTP ${resp.status}`;
    try {
      const e = resp.json;
      if (e == null ? void 0 : e.message) msg = e.message;
      else if (e == null ? void 0 : e.code) msg = e.code;
    } catch {
    }
    throw new Error(msg);
  }
  const user = resp.json;
  if (!(user == null ? void 0 : user.id)) throw new Error("WordPress did not return an authenticated user.");
  if (!wpUserMatchesConfiguredUsername(user, s.wpUsername)) {
    const actual = user.username || user.slug || user.name || `user #${user.id}`;
    throw new Error(`Authenticated as "${actual}", not "${s.wpUsername}". Check the WordPress username.`);
  }
  return user;
}
async function wpRequest(s, method, endpoint, body) {
  const url = `${s.wpUrl.replace(/\/$/, "")}/wp-json/wp/v2/${endpoint}`;
  const resp = await (0, import_obsidian.requestUrl)({
    url,
    method,
    headers: {
      Authorization: basicAuth(s.wpUsername, s.wpPassword),
      "Content-Type": "application/json"
    },
    body: body ? JSON.stringify(body) : void 0,
    throw: false
  });
  if (resp.status >= 400) {
    let msg = `HTTP ${resp.status}`;
    try {
      const e = resp.json;
      if (e == null ? void 0 : e.message) msg = e.message;
      else if (e == null ? void 0 : e.code) msg = e.code;
    } catch (e) {
    }
    throw new Error(msg);
  }
  return resp.json;
}
async function resolveCategory(s, name) {
  const base = s.wpUrl.replace(/\/$/, "");
  const existingId = await findCategoryId(s, name);
  if (existingId) return existingId;
  const cr = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/categories`,
    method: "POST",
    headers: { Authorization: basicAuth(s.wpUsername, s.wpPassword), "Content-Type": "application/json" },
    body: JSON.stringify({ name }),
    throw: false
  });
  if (cr.status >= 400) throw new Error(`Could not create category "${name}"`);
  return cr.json.id;
}
async function findCategoryId(s, name) {
  const base = s.wpUrl.replace(/\/$/, "");
  const sr = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/categories?search=${encodeURIComponent(name)}&per_page=10`,
    method: "GET",
    headers: { Authorization: basicAuth(s.wpUsername, s.wpPassword) },
    throw: false
  });
  if (sr.status === 200) {
    const cats = sr.json;
    const match = cats.find((c) => c.name.toLowerCase() === name.toLowerCase());
    if (match) return match.id;
  }
  return null;
}
function categoryNamesFromFrontmatter(fm) {
  const raw = (fm["category"] || fm["categories"] || "").trim();
  if (!raw) return [];
  return raw.split(",").map((c) => c.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
}
async function resolveCategories(s, fm, createMissingCategories = true) {
  const names = categoryNamesFromFrontmatter(fm);
  if (names.length === 0) return void 0;
  const ids = [];
  for (const name of names) {
    const canonical = canonicalCategoryName(s, name);
    if (createMissingCategories) {
      ids.push(await resolveCategory(s, canonical));
    } else {
      const existingId = await findCategoryId(s, canonical);
      if (existingId) ids.push(existingId);
    }
  }
  return ids;
}
async function fetchWordPressCategoryNames(s) {
  const base = s.wpUrl.replace(/\/$/, "");
  const names = [];
  for (let page = 1; page <= 20; page++) {
    const resp = await (0, import_obsidian.requestUrl)({
      url: `${base}/wp-json/wp/v2/categories?per_page=100&hide_empty=false&_fields=name&page=${page}`,
      method: "GET",
      headers: { Authorization: basicAuth(s.wpUsername, s.wpPassword) },
      throw: false
    });
    if (resp.status === 400 && page > 1) break;
    if (resp.status >= 400) {
      let msg = `HTTP ${resp.status}`;
      try {
        const e = resp.json;
        if (e == null ? void 0 : e.message) msg = e.message;
        else if (e == null ? void 0 : e.code) msg = e.code;
      } catch {
      }
      throw new Error(`Could not load categories (${msg})`);
    }
    const cats = Array.isArray(resp.json) ? resp.json : [];
    names.push(...cats.map((c) => c.name).filter(Boolean));
    if (cats.length < 100) break;
  }
  return mergeCategoryNames([], names);
}
async function findExistingPostByTitle(s, title) {
  var _a;
  const base = s.wpUrl.replace(/\/$/, "");
  const resp = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/posts?search=${encodeURIComponent(title)}&per_page=10&status=any`,
    method: "GET",
    headers: { Authorization: basicAuth(s.wpUsername, s.wpPassword) },
    throw: false
  });
  if (resp.status >= 400) return null;
  const posts = resp.json;
  const match = posts.find((p) => {
    var _a2, _b;
    return ((_b = (_a2 = p.title) == null ? void 0 : _a2.rendered) != null ? _b : "").replace(/<[^>]+>/g, "").trim().toLowerCase() === title.trim().toLowerCase();
  });
  return (_a = match == null ? void 0 : match.id) != null ? _a : null;
}
async function uploadImage(s, app, filePath) {
  var _a;
  const base = s.wpUrl.replace(/\/$/, "");
  const file = app.vault.getAbstractFileByPath(filePath);
  if (!(file instanceof import_obsidian.TFile)) throw new Error(`Image not found: ${filePath}`);
  const binary = await app.vault.readBinary(file);
  const ext = file.extension.toLowerCase();
  const mimeMap = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    gif: "image/gif",
    webp: "image/webp",
    svg: "image/svg+xml"
  };
  const mime = (_a = mimeMap[ext]) != null ? _a : "application/octet-stream";
  const res = await (0, import_obsidian.requestUrl)({
    url: `${base}/wp-json/wp/v2/media`,
    method: "POST",
    headers: {
      Authorization: basicAuth(s.wpUsername, s.wpPassword),
      "Content-Type": mime,
      "Content-Disposition": `attachment; filename="${file.name}"`
    },
    body: binary,
    throw: false
  });
  if (res.status >= 400) throw new Error(`Image upload failed for ${file.name}`);
  return res.json.source_url;
}
async function processImages(app, s, html, sourceFile) {
  const matches = [...html.matchAll(/src="([^"]+)"/g)];
  for (const match of matches) {
    const src = match[1];
    if (/^https?:\/\//.test(src)) continue;
    const resolved = (0, import_obsidian.normalizePath)(sourceFile.parent ? `${sourceFile.parent.path}/${src}` : src);
    try {
      html = html.replace(`src="${src}"`, `src="${await uploadImage(s, app, resolved)}"`);
    } catch (e) {
    }
  }
  const wikiMatches = [...html.matchAll(/!\[\[([^\]]+\.(png|jpe?g|gif|webp|svg))\]\]/gi)];
  for (const match of wikiMatches) {
    const fileName = match[1];
    const found = app.vault.getFiles().find((f) => f.name === fileName || f.path === fileName);
    if (!found) continue;
    try {
      const remoteUrl = await uploadImage(s, app, found.path);
      html = html.replace(match[0], `<img src="${remoteUrl}" alt="${fileName}">`);
    } catch (e) {
    }
  }
  return html;
}
var FolderSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  getItems() {
    const folders = [];
    const recurse = (folder) => {
      folders.push(folder);
      for (const child of folder.children) {
        if (child instanceof import_obsidian.TFolder) recurse(child);
      }
    };
    recurse(this.app.vault.getRoot());
    return folders;
  }
  getItemText(folder) {
    return folder.path === "/" ? "(Vault root)" : folder.path;
  }
  onChooseItem(folder) {
    this.onChoose(folder);
  }
};
var FileSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};
var NewNoteModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit, suggestedName = "Site Post") {
    super(app);
    this.onSubmit = onSubmit;
    this.suggestedName = suggestedName;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "New note from WP template" });
    const wrap = contentEl.createDiv();
    wrap.createEl("label", { text: "Note name:" });
    this.inputEl = wrap.createEl("input", { type: "text", placeholder: "Site Post" });
    this.inputEl.value = this.suggestedName;
    this.inputEl.style.cssText = "width:100%;margin-top:8px;padding:6px;font-size:14px;";
    const btns = contentEl.createDiv();
    btns.style.cssText = "display:flex;gap:8px;margin-top:16px;justify-content:flex-end;";
    btns.createEl("button", { text: "Cancel" }).onclick = () => this.close();
    const ok = btns.createEl("button", { text: "Create note", cls: "mod-cta" });
    ok.onclick = () => {
      this.onSubmit(this.inputEl.value);
      this.close();
    };
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        this.onSubmit(this.inputEl.value);
        this.close();
      }
    });
    this.inputEl.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CategoryEditorSuggest = class extends import_obsidian.EditorSuggest {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onTrigger(cursor, editor) {
    var _a;
    const line = editor.getLine(cursor.line);
    const beforeCursor = line.slice(0, cursor.ch);
    const match = beforeCursor.match(/^(\s*categories?\s*:\s*)(.*)$/i);
    if (!match) return null;
    const valueBefore = match[2];
    const tokenStart = valueBefore.lastIndexOf(",") + 1;
    const token = valueBefore.slice(tokenStart);
    const leadingSpaces = (_a = token.match(/^\s*/)) == null ? void 0 : _a[0].length;
    const query = token.trimStart();
    const startCh = match[1].length + tokenStart + (leadingSpaces != null ? leadingSpaces : 0);
    return {
      start: { line: cursor.line, ch: startCh },
      end: cursor,
      query
    };
  }
  getSuggestions(context) {
    const categories = categoryNamesFromSettings(this.plugin.settings);
    const query = (context.query || "").trim().toLowerCase();
    const matches = categories.filter((c) => !query || c.toLowerCase().includes(query)).slice(0, 25).map((name) => ({ name, isNew: false }));
    if (query && !categories.some((c) => c.toLowerCase() === query)) {
      matches.push({ name: context.query.trim(), isNew: true });
    }
    return matches;
  }
  renderSuggestion(value, el) {
    const row = el.createDiv();
    row.style.cssText = "display:flex;align-items:center;justify-content:space-between;gap:12px;";
    row.createSpan({ text: value.name });
    if (value.isNew) {
      const badge = row.createSpan({ text: "NEW" });
      badge.style.cssText = "font-size:10px;letter-spacing:0.04em;color:var(--text-accent);border:1px solid var(--text-accent);border-radius:4px;padding:1px 5px;";
      badge.title = "This category is not in Known categories. WordPress will create it on publish if it does not already exist.";
    }
  }
  selectSuggestion(value) {
    const context = this.context;
    if (!context) return;
    context.editor.replaceRange(value.name, context.start, context.end);
  }
};
var WPPublisherPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.hotkeyCleanups = [];
    this.internalWriteUntil = {};
    this.pendingCategoryNoticeUntil = {};
    this.pendingCategoryCreateTimers = {};
    this.isRecordingHotkey = false;
    this.ribbonIconEl = null;
  }
  updateRibbonIcon() {
    var _a;
    (_a = this.ribbonIconEl) == null ? void 0 : _a.remove();
    this.ribbonIconEl = null;
    if (!this.settings.showSidebarButton) return;
    this.ribbonIconEl = this.addRibbonIcon("upload-cloud", "Publish to WordPress", () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view == null ? void 0 : view.file) this.publishNote(view.file, "publish");
      else new import_obsidian.Notice("Open a note first.");
    });
  }
  async onload() {
    await this.loadSettings();
    this.updateRibbonIcon();
    this.addCommand({
      id: "wp-publish",
      name: "Publish note to WordPress",
      editorCallback: (_e, view) => {
        if (view.file) this.publishNote(view.file, "publish");
      }
    });
    this.addCommand({
      id: "wp-draft",
      name: "Save note as WordPress draft",
      editorCallback: (_e, view) => {
        if (view.file) this.publishNote(view.file, "draft");
      }
    });
    this.addCommand({
      id: "wp-revert-draft",
      name: "Revert WordPress post to draft",
      editorCallback: (_e, view) => {
        if (view.file) this.revertToDraft(view.file);
      }
    });
    this.addCommand({
      id: "wp-new-from-template",
      name: "New note from template",
      callback: () => this.newNoteFromTemplate()
    });
    this.addCommand({
      id: "wp-apply-template",
      name: "Apply template to current note",
      editorCallback: (_e, view) => {
        if (view.file) this.applyTemplateToCurrentNote(view.file);
      }
    });
    this.addCommand({
      id: "wp-migrate-sync-fields",
      name: "Migrate published notes to WP sync tracking",
      callback: () => this.migrateWpSyncField()
    });
    this.addCommand({
      id: "wp-clear-link",
      name: "Clear WordPress link from current note",
      editorCallback: async (_e, view) => {
        if (!view.file) return;
        await this.forgetWpId(view.file);
        new import_obsidian.Notice("WP-Publisher link cleared for this note.");
      }
    });
    this.registerSavedHotkeys();
    this.registerEditorSuggest(new CategoryEditorSuggest(this.app, this));
    this.updateCategoryCacheNote().catch((e) => console.warn("WP-Publisher category cache update failed", e));
    await this.migrateWpSyncField().catch((e) => console.warn("WP-Publisher wp-sync migration failed", e));
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") return;
        const path = (0, import_obsidian.normalizePath)(file.path);
        const isInternalWrite = (this.internalWriteUntil[path] || 0) > Date.now();
        if (isInternalWrite) {
          return;
        }
        const content = await this.app.vault.read(file);
        const fm = parseFrontmatter(content);
        const wpId = await this.resolveWpId(file, fm);
        if (wpId) {
          const currentHash = postContentFingerprint(content);
          const lastSyncedHash = (this.settings.wpContentHashCache[path] || "").trim();
          const currentSyncState = (fm["wp-sync"] || "").trim().toLowerCase();
          if (!lastSyncedHash && currentSyncState === "synced") {
            this.settings.wpContentHashCache[path] = currentHash;
            await this.saveSettings();
            return;
          }
          const nextSyncState = lastSyncedHash && currentHash === lastSyncedHash ? "synced" : "out-of-sync";
          if (currentSyncState !== nextSyncState) {
            await this.setPluginFrontmatterKey(file, "wp-sync", nextSyncState);
          }
          this.schedulePendingCategoryCreation(file);
        }
        if (this.settings.syncOnSave && wpId) await this.syncStatus(file, wpId);
      })
    );
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") return;
        await this.autoApplyTemplateToNewNote(file);
      })
    );
    this.settingsTab = new WPPublisherSettingTab(this.app, this);
    this.addSettingTab(this.settingsTab);
  }
  onunload() {
    for (const timer of Object.values(this.pendingCategoryCreateTimers)) window.clearTimeout(timer);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async addKnownCategories(names, showNotice = true) {
    const merged = mergeCategoryNames(categoryNamesFromSettings(this.settings), names);
    if (merged.join("\n") === categoryNamesFromSettings(this.settings).join("\n")) return;
    this.settings.wpCategories = merged.join("\n");
    this.settings.wpCategoriesLastRefreshedAt = Date.now();
    this.settings.wpCategoriesLastSource = "wordpress";
    this.settings.wpCategoriesLastWordPressSnapshot = normalizedCategorySnapshot(merged);
    this.settings.wpCategoriesLastMessage = `Updated from WordPress: ${names.join(", ")}`;
    await this.saveSettings();
    await this.updateCategoryCacheNote();
    this.settingsTab?.refreshCategoryList();
    if (showNotice) new import_obsidian.Notice(`Added to Known categories: ${names.join(", ")}`, 6e3);
  }
  notifyPendingUnknownCategories(file, fm) {
    const unknownCategories = unknownCategoryNames(this.settings, categoryNamesFromFrontmatter(fm));
    if (unknownCategories.length === 0) return;
    const path = (0, import_obsidian.normalizePath)(file.path);
    const now = Date.now();
    if ((this.pendingCategoryNoticeUntil[path] || 0) > now) return;
    this.pendingCategoryNoticeUntil[path] = now + 3e4;
    const statusName = (fm["status"] || "unknown").trim() || "unknown";
    const message = this.settings.autoCreateCategories ? `This post is currently ${statusName}, but this category has not been created yet: ${unknownCategories.join(", ")}. Publish or save as draft to create/update it in WordPress.` : `This post is currently ${statusName}, and this category is not in the list: ${unknownCategories.join(", ")}. Automatic category creation is off.`;
    new import_obsidian.Notice(message, 12e3);
  }
  schedulePendingCategoryCreation(file) {
    const path = (0, import_obsidian.normalizePath)(file.path);
    if (this.pendingCategoryCreateTimers[path]) {
      window.clearTimeout(this.pendingCategoryCreateTimers[path]);
    }
    this.pendingCategoryCreateTimers[path] = window.setTimeout(() => {
      delete this.pendingCategoryCreateTimers[path];
      this.createMissingCategoriesForFile(file).catch((e) => {
        console.warn("WP-Publisher category auto-create failed", e);
        new import_obsidian.Notice(`Category auto-create failed: ${e instanceof Error ? e.message : String(e)}`, 1e4);
      });
    }, 1500);
  }
  async createMissingCategoriesForFile(file) {
    if (!this.settings.autoCreateCategories) return;
    const validErr = this.validateSettings();
    await flushPendingObsidianPropertyEdit();
    const content = await this.app.vault.read(file);
    const fm = parseFrontmatter(content);
    const wpId = await this.resolveWpId(file, fm);
    if (!wpId) return;
    const unknownCategories = unknownCategoryNames(this.settings, categoryNamesFromFrontmatter(fm));
    if (unknownCategories.length === 0) return;
    if (validErr) {
      this.notifyPendingUnknownCategories(file, fm);
      throw new Error(validErr);
    }
    for (const name of unknownCategories) {
      await resolveCategory(this.settings, name);
    }
    await this.addKnownCategories(unknownCategories, false);
    const statusName = (fm["status"] || "unknown").trim() || "unknown";
    new import_obsidian.Notice(`Created/confirmed WordPress ${unknownCategories.length === 1 ? "category" : "categories"} for ${statusName} post: ${unknownCategories.join(", ")}`, 8e3);
  }
  async setPluginFrontmatterKey(file, key, value) {
    const path = (0, import_obsidian.normalizePath)(file.path);
    this.internalWriteUntil[path] = Date.now() + 1500;
    await setFrontmatterKey(this.app, file, key, value);
  }
  async migrateWpSyncField() {
    let updated = 0;
    const migrationVersion = this.settings.wpSyncMigrationVersion || 0;
    const firstMigration = migrationVersion < 1;
    const baselineMigration = migrationVersion < 3;
    for (const file of this.app.vault.getMarkdownFiles()) {
      const path = (0, import_obsidian.normalizePath)(file.path);
      const content = await this.app.vault.read(file);
      const fm = parseFrontmatter(content);
      const cachedId = (this.settings.wpIdCache[path] || "").trim();
      const frontmatterId = (fm["wp-id"] || "").trim();
      const syncMarker = (fm["wp-sync"] || "").trim();
      const wpId = frontmatterId || (syncMarker ? cachedId : "");
      if (!wpId) continue;
      if (!cachedId && frontmatterId) {
        this.settings.wpIdCache[path] = frontmatterId;
      }
      if (baselineMigration) {
        this.settings.wpContentHashCache[path] = postContentFingerprint(content);
      }
      if (cachedId && frontmatterId !== cachedId) {
        await this.setPluginFrontmatterKey(file, "wp-id", cachedId);
      }
      if (firstMigration || baselineMigration || !syncMarker) {
        await this.setPluginFrontmatterKey(file, "wp-sync", "synced");
      }
      updated++;
    }
    if (baselineMigration) {
      this.settings.wpSyncMigrationVersion = 3;
    }
    if (updated > 0) {
      await this.saveSettings();
      new import_obsidian.Notice(`WP-Publisher migrated ${updated} published note${updated === 1 ? "" : "s"} to wp-sync tracking.`);
    } else if (baselineMigration) {
      await this.saveSettings();
    }
  }
  async resolveWpId(file, fm) {
    const path = (0, import_obsidian.normalizePath)(file.path);
    const cached = (this.settings.wpIdCache[path] || "").trim();
    const fmId = (fm["wp-id"] || "").trim();
    const syncMarker = (fm["wp-sync"] || "").trim();
    if (cached) {
      if (!fmId && !syncMarker) return null;
      if (fmId !== cached) {
        await this.setPluginFrontmatterKey(file, "wp-id", cached);
      }
      return cached;
    }
    if (!fmId) return null;
    this.settings.wpIdCache[path] = fmId;
    await this.saveSettings();
    await this.setPluginFrontmatterKey(file, "wp-id", fmId);
    return fmId;
  }
  async storeWpId(file, wpId) {
    const path = (0, import_obsidian.normalizePath)(file.path);
    this.settings.wpIdCache[path] = wpId;
    await this.saveSettings();
    await this.setPluginFrontmatterKey(file, "wp-id", wpId);
  }
  async storeSyncedContentHash(file, content) {
    const path = (0, import_obsidian.normalizePath)(file.path);
    this.settings.wpContentHashCache[path] = postContentFingerprint(content);
    await this.saveSettings();
  }
  async forgetWpId(file) {
    const path = (0, import_obsidian.normalizePath)(file.path);
    if (this.settings.wpIdCache[path]) {
      delete this.settings.wpIdCache[path];
      await this.saveSettings();
    }
    if (this.settings.wpContentHashCache[path]) {
      delete this.settings.wpContentHashCache[path];
      await this.saveSettings();
    }
    await deleteFrontmatterKey(this.app, file, "wp-id");
    await deleteFrontmatterKey(this.app, file, "wp-sync");
  }
  getNextSitePostPath(folder) {
    const normalizedFolder = (0, import_obsidian.normalizePath)(folder);
    const prefix = normalizedFolder && normalizedFolder !== "/" ? `${normalizedFolder}/` : "";
    let index = 1;
    while (true) {
      const baseName = `Site Post ${index}`;
      const path = (0, import_obsidian.normalizePath)(`${prefix}${baseName}.md`);
      if (!this.app.vault.getAbstractFileByPath(path)) return path;
      index++;
    }
  }
  async ensureFolderPath(folderPath) {
    const normalized = (0, import_obsidian.normalizePath)(folderPath);
    if (!normalized || normalized === "/") return;
    const parts = normalized.split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (existing instanceof import_obsidian.TFolder) continue;
      if (existing) throw new Error(`Cannot create folder "${current}" because a file already exists there.`);
      await this.app.vault.createFolder(current);
    }
  }
  // ── Hotkeys registered from stored combos ──
  async updateCategoryCacheNote() {
    const names = Array.from(new Map(categoryNamesFromSettings(this.settings).map((c) => [c.toLowerCase(), c])).values()).sort((a, b) => a.localeCompare(b));
    const templatePath = (this.settings.defaultTemplatePath || "").trim();
    const templateFolder = templatePath ? templatePath.split("/").slice(0, -1).join("/") : "";
    const cacheFolder = templateFolder || (this.settings.publishFolder || "").trim() || "";
    const cachePath = (0, import_obsidian.normalizePath)(`${cacheFolder ? `${cacheFolder}/` : ""}WP-Publisher Category Cache.md`);
    await this.ensureFolderPath(cachePath.split("/").slice(0, -1).join("/"));
    const yamlList = names.length ? names.map((name) => `  - "${name.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join("\n") : "[]";
    const categoryBlock = names.length ? `category:
${yamlList}
categories:
${yamlList}` : "category: []\ncategories: []";
    const content = `---
${categoryBlock}
wp-publisher-internal: category-cache
---
# WP-Publisher Category Cache

This note is maintained by WP-Publisher so Obsidian's native property dropdown can suggest known WordPress categories.

Edit categories in Settings -> WP-Publisher -> Categories. You can ignore this note.
`;
    for (const file of this.app.vault.getMarkdownFiles()) {
      const path = (0, import_obsidian.normalizePath)(file.path);
      if (path === cachePath) continue;
      const current = await this.app.vault.read(file);
      if (current.includes("wp-publisher-internal: category-cache")) {
        await this.app.vault.delete(file);
      }
    }
    const existing = this.app.vault.getAbstractFileByPath(cachePath);
    if (existing instanceof import_obsidian.TFile) {
      const current = await this.app.vault.read(existing);
      if (current !== content) await this.app.vault.modify(existing, content);
    } else if (!existing) {
      await this.app.vault.create(cachePath, content);
    }
  }
  registerSavedHotkeys() {
    for (const cleanup of this.hotkeyCleanups) cleanup();
    this.hotkeyCleanups = [];
    const tryHotkey = (hk, action) => {
      if (!hk) return;
      const handler = (e) => {
        if (this.isRecordingHotkey) return;
        const pressed = eventToHotkey(e);
        if (!pressed) return;
        if (pressed.key === hk.key && pressed.modifiers.length === hk.modifiers.length && hk.modifiers.every((m) => pressed.modifiers.includes(m))) {
          e.preventDefault();
          action();
        }
      };
      document.addEventListener("keydown", handler, true);
      this.hotkeyCleanups.push(() => document.removeEventListener("keydown", handler, true));
    };
    tryHotkey(this.settings.hotkeyPublish, () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view == null ? void 0 : view.file) this.publishNote(view.file, "publish");
    });
    tryHotkey(this.settings.hotkeyDraft, () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view == null ? void 0 : view.file) this.publishNote(view.file, "draft");
    });
  }
  // ── Validate settings ──
  validateSettings() {
    if (!this.settings.wpUrl) return "WordPress URL is not set. Go to Settings \u2192 WP-Publisher.";
    if (!this.settings.wpUsername) return "WordPress username is not set.";
    if (!this.settings.wpPassword) return "WordPress application password is not set.";
    try {
      new URL(this.settings.wpUrl);
    } catch (e) {
      return "WordPress URL is invalid \u2014 include https://, e.g. https://mysite.com";
    }
    return null;
  }
  // ── Folder check ──
  publishFolderError() {
    const folder = this.settings.publishFolder.trim();
    if (!folder || folder === "/") return "Publish folder is not set. Go to Settings \u2192 WP-Publisher and choose a dedicated folder.";
    return null;
  }
  fileIsAllowed(file) {
    var _a;
    const folder = this.settings.publishFolder.trim();
    if (!folder || folder === "/") return false;
    return file.path.startsWith(folder + "/") || ((_a = file.parent) == null ? void 0 : _a.path) === folder;
  }
  // ── Publish / update ──
  async publishNote(file, desiredStatus) {
    const err = this.validateSettings();
    if (err) {
      new import_obsidian.Notice(`\u26D4 ${err}`, 8e3);
      return;
    }
    const folderErr = this.publishFolderError();
    if (folderErr) {
      new import_obsidian.Notice(`\u26D4 ${folderErr}`, 1e4);
      return;
    }
    if (!this.fileIsAllowed(file)) {
      const folder = this.settings.publishFolder;
      new import_obsidian.Notice(`\u26D4 This note is not in the publish folder:
"${folder}"

Change the folder in Settings \u2192 WP-Publisher, or move the note.`, 1e4);
      return;
    }
    await flushPendingObsidianPropertyEdit();
    const content = await this.app.vault.read(file);
    const fm = parseFrontmatter(content);
    let html = mdToHtml(stripFrontmatter(content));
    try {
      html = await processImages(this.app, this.settings, html, file);
    } catch (e) {
    }
    const title = fm["title"] || file.basename;
    const payload = {
      title,
      content: html,
      status: desiredStatus,
      excerpt: fm["excerpt"] || ""
    };
    const commentStatus = getCommentStatus(fm);
    if (commentStatus) payload["comment_status"] = commentStatus;
    const previousStatus = (fm["status"] || "").trim().toLowerCase();
    try {
      const unknownCategories = unknownCategoryNames(this.settings, categoryNamesFromFrontmatter(fm));
      if (unknownCategories.length > 0) {
        const message = this.settings.autoCreateCategories ? `Not in Known categories; WordPress will create if missing: ${unknownCategories.join(", ")}` : `Not in Known categories and automatic category creation is off: ${unknownCategories.join(", ")}`;
        new import_obsidian.Notice(message, 8e3);
      }
      const categoryIds = await resolveCategories(this.settings, fm, this.settings.autoCreateCategories);
      if (categoryIds) payload["categories"] = categoryIds;
      const existingId = await this.resolveWpId(file, fm) || await findExistingPostByTitle(this.settings, title);
      let post;
      if (existingId) {
        post = await wpRequest(this.settings, "POST", `posts/${existingId}`, payload);
        await this.storeWpId(file, String(post.id));
        const msg = desiredStatus === "draft" ? previousStatus === "publish" ? "Taken down to draft" : "Draft updated" : previousStatus === "draft" ? "Published from draft" : "Post updated";
        new import_obsidian.Notice(`\u2705 ${msg}: "${title}"`);
      } else {
        post = await wpRequest(this.settings, "POST", "posts", payload);
        await this.storeWpId(file, String(post.id));
        new import_obsidian.Notice(desiredStatus === "publish" ? `\u2705 Published: "${title}"` : `\u2705 Saved as new draft: "${title}"`);
      }
      if (unknownCategories.length > 0 && this.settings.autoCreateCategories) {
        try {
          await this.addKnownCategories(unknownCategories);
        } catch (categoryUpdateError) {
          console.warn("WP-Publisher could not update Known categories after publish", categoryUpdateError);
          new import_obsidian.Notice("Post succeeded, but WP-Publisher could not refresh Known categories. Reload or use Replace from WordPress.", 1e4);
        }
      }
      await this.storeSyncedContentHash(file, content);
      await this.setPluginFrontmatterKey(file, "status", post.status);
      await this.setPluginFrontmatterKey(file, "wp-sync", "synced");
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      await this.setPluginFrontmatterKey(file, "status", "error");
      new import_obsidian.Notice(`\u26D4 Publish failed: ${msg}`, 1e4);
    }
  }
  // ── Revert to draft ──
  async revertToDraft(file) {
    const err = this.validateSettings();
    if (err) {
      new import_obsidian.Notice(`\u26D4 ${err}`, 8e3);
      return;
    }
    const folderErr = this.publishFolderError();
    if (folderErr) {
      new import_obsidian.Notice(`\u26D4 ${folderErr}`, 1e4);
      return;
    }
    if (!this.fileIsAllowed(file)) {
      const folder = this.settings.publishFolder;
      new import_obsidian.Notice(`\u26D4 This note is not in the publish folder:
"${folder}"

Change the folder in Settings \u2192 WP-Publisher, or move the note.`, 1e4);
      return;
    }
    const content = await this.app.vault.read(file);
    const fm = parseFrontmatter(content);
    const wpId = await this.resolveWpId(file, fm);
    if (!wpId) {
      new import_obsidian.Notice("\u26D4 This note hasn't been published yet (no wp-id).");
      return;
    }
    try {
      await wpRequest(this.settings, "POST", `posts/${wpId}`, { status: "draft" });
      await this.setPluginFrontmatterKey(file, "status", "draft");
      new import_obsidian.Notice(`\u2705 Reverted to draft: "${fm["title"] || file.basename}"`);
    } catch (e) {
      new import_obsidian.Notice(`\u26D4 Revert failed: ${e instanceof Error ? e.message : String(e)}`, 1e4);
    }
  }
  // ── Sync on save ──
  async syncStatus(file, wpId) {
    try {
      const post = await wpRequest(this.settings, "GET", `posts/${wpId}`);
      await this.setPluginFrontmatterKey(file, "status", post.status);
    } catch (e) {
    }
  }
  // ── Template helpers ──
  async getTemplateContent() {
    const templatePath = this.settings.defaultTemplatePath.trim();
    if (!templatePath) return buildDefaultTemplate(this.settings);
    const templateFile = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(templatePath));
    if (!(templateFile instanceof import_obsidian.TFile)) {
      throw new Error(`Template note not found: "${templatePath}". Check the path in Settings \u2192 WP-Publisher.`);
    }
    return await this.app.vault.read(templateFile);
  }
  // ── New note from template ──
  async newNoteFromTemplate() {
    const folderErr = this.publishFolderError();
    if (folderErr) {
      new import_obsidian.Notice(`\u26D4 ${folderErr}`, 1e4);
      return;
    }
    let templateContent;
    try {
      templateContent = await this.getTemplateContent();
    } catch (e) {
      new import_obsidian.Notice(`\u26D4 ${e instanceof Error ? e.message : String(e)}`, 1e4);
      return;
    }
    const folder = this.settings.publishFolder.trim();
    const suggestedName = this.getNextSitePostPath(folder).split("/").pop()?.replace(/\.md$/i, "") || "Site Post";
    new NewNoteModal(this.app, async (noteName) => {
      if (!noteName.trim()) {
        new import_obsidian.Notice("Note name cannot be empty.");
        return;
      }
      const fileName = noteName.endsWith(".md") ? noteName : `${noteName}.md`;
      const newPath = (0, import_obsidian.normalizePath)(`${folder}/${fileName}`);
      try {
        const newFile = await this.app.vault.create(newPath, templateContent);
        await this.app.workspace.getLeaf(false).openFile(newFile);
        new import_obsidian.Notice(`\u2705 Created "${noteName}" from template.`);
      } catch (e) {
        new import_obsidian.Notice(`\u26D4 Could not create note: ${e instanceof Error ? e.message : String(e)}`, 8e3);
      }
    }, suggestedName).open();
  }
  async applyTemplateToCurrentNote(file) {
    try {
      const existing = await this.app.vault.read(file);
      if (existing.trim().length > 0 && !confirm("This note already has content. Add the WP template to the top anyway?")) return;
      const templateContent = await this.getTemplateContent();
      await this.app.vault.modify(file, `${templateContent.trim()}

${existing}`.trimEnd() + "\n");
      new import_obsidian.Notice(`\u2705 WP-Publisher template applied to "${file.basename}".`);
    } catch (e) {
      new import_obsidian.Notice(`\u26D4 Could not apply template: ${e instanceof Error ? e.message : String(e)}`, 1e4);
    }
  }
  async autoApplyTemplateToNewNote(file) {
    if (!this.settings.autoApplyTemplateOnNewNotes) return;
    const folder = this.settings.publishFolder.trim();
    if (!folder || folder === "/") return;
    if (!this.fileIsAllowed(file)) return;
    const templatePath = this.settings.defaultTemplatePath.trim();
    if (templatePath && (0, import_obsidian.normalizePath)(templatePath) === file.path) return;
    try {
      await wait(250);
      const existing = await this.app.vault.read(file);
      if (existing.trim().length > 0) return;
      let targetFile = file;
      if (/^Untitled(?: \d+)?$/i.test(file.basename)) {
        const newPath = this.getNextSitePostPath(folder);
        if (newPath !== file.path) {
          await this.app.fileManager.renameFile(file, newPath);
          const moved = this.app.vault.getAbstractFileByPath(newPath);
          if (moved instanceof import_obsidian.TFile) targetFile = moved;
        }
      }
      const templateContent = await this.getTemplateContent();
      await this.app.vault.modify(targetFile, templateContent.trimEnd() + "\n");
      new import_obsidian.Notice(`WP template applied to new post note: "${targetFile.basename}".`);
    } catch (e) {
      new import_obsidian.Notice(`Could not auto-apply WP template: ${e instanceof Error ? e.message : String(e)}`, 1e4);
    }
  }
};
var WPPublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  refreshCategoryList() {
    if (this.categoryTextAreaEl && this.categoryTextAreaEl.value !== this.plugin.settings.wpCategories) {
      this.categoryTextAreaEl.value = this.plugin.settings.wpCategories;
    }
    this.refreshCategoryStatus();
  }
  refreshCategoryStatus() {
    const categoryCount = categoryNamesFromSettings(this.plugin.settings).length;
    const source = this.plugin.settings.wpCategoriesLastSource === "wordpress" ? "WordPress" : "Manual";
    const currentSnapshot = normalizedCategorySnapshot(this.plugin.settings.wpCategories);
    const lastSnapshot = this.plugin.settings.wpCategoriesLastWordPressSnapshot || "";
    const status = this.plugin.settings.wpCategoriesLastSource === "wordpress" && currentSnapshot === lastSnapshot ? "in sync" : "needs refresh";
    if (this.categoryInlineStatusEl) {
      this.categoryInlineStatusEl.empty();
      const message = this.plugin.settings.wpCategoriesLastMessage || "No category updates yet";
      this.categoryInlineStatusEl.createEl("div", { text: message }).style.cssText = "font-weight:600;color:var(--text-normal);";
      this.categoryInlineStatusEl.createEl("div", { text: `Refresh state: ${status}` });
    }
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.plugin.updateCategoryCacheNote().catch((e) => console.warn("WP-Publisher category cache update failed", e));
    containerEl.createEl("h2", { text: `WordPress connection \u2014 WP-Publisher ${WP_PUBLISHER_VERSION}` });
    new import_obsidian.Setting(containerEl).setName("Site URL").setDesc("Full URL including https://, e.g. https://mysite.com").addText(
      (t) => t.setPlaceholder("https://mysite.com").setValue(this.plugin.settings.wpUrl).onChange(async (v) => {
        this.plugin.settings.wpUrl = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Username").setDesc("Your WordPress login username").addText(
      (t) => t.setPlaceholder("admin").setValue(this.plugin.settings.wpUsername).onChange(async (v) => {
        this.plugin.settings.wpUsername = v.trim();
        await this.plugin.saveSettings();
      })
    );
    const passwordIsLocked = this.plugin.settings.wpPassword.trim().length > 0;
    let pendingPassword = "";
    let passwordInputEl = null;
    const passwordSetting = new import_obsidian.Setting(containerEl).setName("Application password").setDesc(passwordIsLocked ? "Saved and locked. The password is not shown here again. Clear it before entering a replacement." : "Paste the one-time WordPress Application Password, then click Lock password. Different from your login password.").addText((t) => {
      passwordInputEl = t.inputEl;
      t.setPlaceholder(passwordIsLocked ? "Password saved and locked" : "xxxx xxxx xxxx xxxx xxxx xxxx").setValue("").onChange((v) => {
        pendingPassword = v.trim();
      });
      t.inputEl.type = "password";
      t.inputEl.disabled = passwordIsLocked;
      t.inputEl.autocomplete = "new-password";
    }).addButton(
      (btn) => btn.setButtonText("?").setTooltip("What is this?").onClick(() => {
        new import_obsidian.Notice("Use a WordPress Application Password. Paste it once, click Lock password, and the plugin hides it. To change it later, click Clear password and paste a new one.", 12e3);
      })
    );
    if (!passwordIsLocked) {
      passwordSetting.addButton(
        (btn) => btn.setButtonText("Show").setTooltip("Temporarily show/hide what you typed before locking").onClick(() => {
          if (!passwordInputEl) return;
          const showing = passwordInputEl.type === "text";
          passwordInputEl.type = showing ? "password" : "text";
          btn.setButtonText(showing ? "Show" : "Hide");
        })
      ).addButton(
        (btn) => btn.setButtonText("Lock password").setCta().onClick(async () => {
          if (!pendingPassword) {
            new import_obsidian.Notice("Paste the WordPress application password first, then click Lock password.", 8e3);
            return;
          }
          this.plugin.settings.wpPassword = pendingPassword;
          await this.plugin.saveSettings();
          pendingPassword = "";
          new import_obsidian.Notice("\u2705 Application password saved and locked. It will not be shown in settings again.", 8e3);
          this.display();
        })
      );
    } else {
      passwordSetting.addButton(
        (btn) => btn.setButtonText("Clear password").setWarning().onClick(async () => {
          this.plugin.settings.wpPassword = "";
          await this.plugin.saveSettings();
          new import_obsidian.Notice("Application password cleared. Paste a new one and click Lock password to replace it.", 8e3);
          this.display();
        })
      );
    }
    const testRow = containerEl.createDiv();
    testRow.style.marginBottom = "16px";
    const testBtn = testRow.createEl("button", { text: "Test connection", cls: "mod-cta" });
    const testResult = testRow.createEl("span");
    testResult.style.cssText = "margin-left:12px;font-size:13px;";
    testBtn.onclick = async () => {
      testResult.textContent = "Testing\u2026";
      const validErr = this.plugin.validateSettings();
      if (validErr) {
        testResult.textContent = `\u26D4 ${validErr}`;
        return;
      }
      try {
        await testWordPressConnection(this.plugin.settings);
        testResult.textContent = "\u2705 Connected";
      } catch (e) {
        testResult.textContent = `\u26D4 ${e instanceof Error ? e.message : String(e)}`;
      }
    };
    containerEl.createEl("h2", { text: "Publishing rules" });
    const folderSetting = new import_obsidian.Setting(containerEl).setName("Publish folder").setDesc("Only notes in this folder can be published or drafted. Choose a dedicated folder for WordPress posts.").addText((t) => {
      t.setPlaceholder("Posts").setValue(this.plugin.settings.publishFolder).onChange(async (v) => {
        var _a;
        this.plugin.settings.publishFolder = v.trim();
        await this.plugin.saveSettings();
        (_a = folderSetting.settingEl.querySelector(".wp-folder-label")) == null ? void 0 : _a.remove();
      });
      return t;
    }).addButton(
      (btn) => btn.setButtonText("Browse\u2026").onClick(() => {
        new FolderSuggestModal(this.app, async (folder) => {
          if (folder.path === "/") {
            new import_obsidian.Notice("Choose a dedicated publish folder, not the vault root.", 8e3);
            return;
          }
          const path = folder.path;
          this.plugin.settings.publishFolder = path;
          await this.plugin.saveSettings();
          this.display();
        }).open();
      })
    );
    if (this.plugin.settings.publishFolder) {
      const badge = folderSetting.settingEl.createEl("div", {
        cls: "wp-folder-label",
        text: `\u{1F4C1} ${this.plugin.settings.publishFolder}`
      });
      badge.style.cssText = "font-size:12px;color:var(--text-muted);margin-top:4px;";
    }
    containerEl.createEl("h2", { text: "Template" });
    const tplSetting = new import_obsidian.Setting(containerEl).setName("Default template note").setDesc("Path to a note used as the template for new posts. Leave blank to use the built-in WP-Publisher template. The note filename is used as the WordPress title.").addText((t) => {
      t.setPlaceholder("Templates/WP Post.md").setValue(this.plugin.settings.defaultTemplatePath).onChange(async (v) => {
        this.plugin.settings.defaultTemplatePath = v.trim();
        await this.plugin.saveSettings();
        this.refreshTemplateStatus(tplSetting.settingEl);
      });
      return t;
    }).addButton(
      (btn) => btn.setButtonText("Browse\u2026").onClick(() => {
        new FileSuggestModal(this.app, async (file) => {
          this.plugin.settings.defaultTemplatePath = file.path;
          await this.plugin.saveSettings();
          this.display();
        }).open();
      })
    );
    this.refreshTemplateStatus(tplSetting.settingEl);
    new import_obsidian.Setting(containerEl).setName("Apply template to new notes in publish folder").setDesc("When enabled, ordinary blank notes created inside the publish folder automatically receive the selected WP template. Existing/non-empty notes are left alone.").addToggle(
      (t) => t.setValue(this.plugin.settings.autoApplyTemplateOnNewNotes).onChange(async (v) => {
        this.plugin.settings.autoApplyTemplateOnNewNotes = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync status on save").setDesc("Silently update status: in frontmatter whenever you save a note with a plugin-managed wp-id.").addToggle(
      (t) => t.setValue(this.plugin.settings.syncOnSave).onChange(async (v) => {
        this.plugin.settings.syncOnSave = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Categories" });
    containerEl.createEl("p", {
      text: "Add known WordPress categories here. Put each category on its own line, or separate categories with commas."
    }).style.cssText = "font-size:13px;color:var(--text-muted);margin-bottom:8px;";
    new import_obsidian.Setting(containerEl).setName("Automatically create missing categories").setDesc("If enabled, missing categories are created in WordPress when a note is published or drafted, and for linked posts when category edits settle.").addToggle(
      (t) => t.setValue(this.plugin.settings.autoCreateCategories).onChange(async (v) => {
        this.plugin.settings.autoCreateCategories = v;
        await this.plugin.saveSettings();
      })
    );
    const categorySetting = new import_obsidian.Setting(containerEl).setName("Known categories").setDesc("Used for category suggestions while typing category: or categories: in note frontmatter.");
    categorySetting.addTextArea((t) => {
      t.setPlaceholder("Blog\nNews\nProjects").setValue(this.plugin.settings.wpCategories).onChange(async (v) => {
        this.plugin.settings.wpCategories = v;
        this.plugin.settings.wpCategoriesLastSource = "manual";
        this.plugin.settings.wpCategoriesLastMessage = "Edited Known categories manually.";
        await this.plugin.saveSettings();
        await this.plugin.updateCategoryCacheNote();
        this.refreshCategoryList();
      });
      t.inputEl.rows = 6;
      t.inputEl.style.width = "100%";
      t.inputEl.style.minWidth = "360px";
      t.inputEl.style.resize = "vertical";
      this.categoryTextAreaEl = t.inputEl;
    });
    categorySetting.addButton((btn) => {
      btn.setButtonText("?").setTooltip("Category list format").onClick(() => {
        const behavior = this.plugin.settings.autoCreateCategories ? "If a note is published or drafted and the category is not in the list, the category is created automatically in WordPress." : "If automatic category creation is off, only categories that already exist in WordPress will be assigned on publish or draft.";
        new import_obsidian.Notice(`Use one category per line or separate them with commas. ${behavior}`, 12e3);
      });
    });
    categorySetting.addButton((btn) => {
      btn.setButtonText("Refresh from WordPress").setCta().setTooltip("Replace Known categories with the current WordPress category list.").onClick(async () => {
        const validErr = this.plugin.validateSettings();
        if (validErr) {
          new import_obsidian.Notice(`\u26D4 ${validErr}`, 8e3);
          return;
        }
        try {
          const loaded = await fetchWordPressCategoryNames(this.plugin.settings);
          const merged = mergeCategoryNames([], loaded);
          this.plugin.settings.wpCategories = merged.join("\n");
          this.plugin.settings.wpCategoriesLastRefreshedAt = Date.now();
          this.plugin.settings.wpCategoriesLastSource = "wordpress";
          this.plugin.settings.wpCategoriesLastWordPressSnapshot = normalizedCategorySnapshot(merged);
          this.plugin.settings.wpCategoriesLastMessage = `Replaced Known categories from WordPress. ${merged.length} categories loaded.`;
          await this.plugin.saveSettings();
          await this.plugin.updateCategoryCacheNote();
          this.refreshCategoryList();
          new import_obsidian.Notice(`\u2705 Loaded ${loaded.length} categories from WordPress.`);
        } catch (e) {
          this.plugin.settings.wpCategoriesLastMessage = `Category refresh failed: ${e instanceof Error ? e.message : String(e)}`;
          await this.plugin.saveSettings();
          this.refreshCategoryStatus();
          new import_obsidian.Notice(`\u26D4 Category load failed: ${e instanceof Error ? e.message : String(e)}`, 1e4);
        }
      });
    });
    categorySetting.settingEl.style.alignItems = "stretch";
    categorySetting.infoEl.style.alignSelf = "flex-start";
    categorySetting.controlEl.style.flexDirection = "column";
    categorySetting.controlEl.style.alignItems = "stretch";
    categorySetting.controlEl.style.gap = "8px";
    const categoryButtonRow = categorySetting.controlEl.createDiv();
    categoryButtonRow.style.cssText = "display:flex;gap:8px;justify-content:flex-end;";
    const categoryButtons = Array.from(categorySetting.controlEl.querySelectorAll("button"));
    for (const button of categoryButtons) categoryButtonRow.appendChild(button);
    this.categoryInlineStatusEl = categorySetting.controlEl.createDiv();
    this.categoryInlineStatusEl.style.cssText = "font-size:12px;color:var(--text-muted);padding:8px 2px 0 2px;line-height:1.6;";
    this.refreshCategoryStatus();
    containerEl.createEl("h2", { text: "Hotkeys" });
    containerEl.createEl("p", {
      text: "Click Record, press your desired key combination, then click Stop recording to save it. Press Escape to cancel recording."
    }).style.cssText = "font-size:13px;color:var(--text-muted);margin-bottom:12px;";
    this.addHotkeySetting(containerEl, "Publish hotkey", "hotkeyPublish");
    this.addHotkeySetting(containerEl, "Draft hotkey", "hotkeyDraft");
    new import_obsidian.Setting(containerEl).setName("Show sidebar publish button").setDesc("Show or hide the WP-Publisher button in Obsidian's left sidebar.").addToggle(
      (t) => t.setValue(this.plugin.settings.showSidebarButton).onChange(async (v) => {
        this.plugin.settings.showSidebarButton = v;
        await this.plugin.saveSettings();
        this.plugin.updateRibbonIcon();
      })
    );
    containerEl.createEl("p", {
      text: "You can also assign hotkeys via Obsidian's built-in Settings \u2192 Hotkeys page \u2014 search for 'WP-Publisher' to find all commands there."
    }).style.cssText = "font-size:12px;color:var(--text-muted);margin-top:8px;";
    containerEl.createEl("h2", { text: "Frontmatter keys" });
    const info = containerEl.createEl("div");
    info.style.cssText = "font-size:13px;color:var(--text-muted);line-height:1.8;";
    info.innerHTML = `
			<code>title:</code> \u2014 optional override; by default the post title comes from the note filename<br>
			<code>category:</code> \u2014 WordPress category (auto-created if new; blank uses WordPress Uncategorized)<br>
			<code>excerpt:</code> \u2014 post summary / meta description<br>
			<code>comments:</code> \u2014 <code>on</code> or <code>off</code>; sends WordPress comment_status open/closed for anti-bot control<br>
			<code>status:</code> \u2014 updated automatically by the plugin<br>
			<code>wp-id:</code> \u2014 visible publish marker, managed automatically by WP-Publisher<br>
			<code>wp-sync:</code> \u2014 <code>synced</code> after publish/draft; <code>out-of-sync</code> after local edits<br>
		`;
    const footer = containerEl.createEl("div");
    footer.style.cssText = "margin-top:24px;padding-top:12px;border-top:1px solid var(--background-modifier-border);font-size:12px;color:var(--text-muted);";
    footer.createSpan({ text: "WP-Publisher on GitHub: " });
    const githubLink = footer.createEl("a", {
      text: "github",
      href: "https://github.com/Wicked-Shrapnel/Obsidian-2-WordPress-Plugin"
    });
    githubLink.setAttr("target", "_blank");
    githubLink.setAttr("rel", "noopener");
  }
  // Show a green ✅ or red ⛔ next to the template path
  refreshTemplateStatus(settingEl) {
    var _a;
    (_a = settingEl.querySelector(".wp-tpl-status")) == null ? void 0 : _a.remove();
    const path = this.plugin.settings.defaultTemplatePath.trim();
    if (!path) return;
    const exists = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(path)) instanceof import_obsidian.TFile;
    const span = settingEl.createEl("span", {
      cls: "wp-tpl-status",
      text: exists ? "\u2705 Found" : "\u26D4 Not found \u2014 check the path"
    });
    span.style.cssText = `font-size:12px;margin-left:8px;color:${exists ? "var(--color-green)" : "var(--color-red)"};`;
  }
  // Build a single hotkey recorder row
  addHotkeySetting(container, label, settingKey) {
    const current = this.plugin.settings[settingKey];
    const row = new import_obsidian.Setting(container).setName(label);
    const display = row.controlEl.createEl("span");
    display.style.cssText = "min-width:160px;display:inline-block;font-size:13px;padding:4px 8px;background:var(--background-modifier-form-field);border-radius:4px;border:1px solid var(--background-modifier-border);";
    display.textContent = hotkeyLabel(current);
    let recording = false;
    let pendingHotkey = null;
    let keyHandler = null;
    const detachRecorder = () => {
      recording = false;
      this.plugin.isRecordingHotkey = false;
      recordBtn.classList.remove("mod-warning");
      if (keyHandler) {
        document.removeEventListener("keydown", keyHandler, true);
        document.removeEventListener("keyup", keyHandler, true);
        window.removeEventListener("keydown", keyHandler, true);
        window.removeEventListener("keyup", keyHandler, true);
        keyHandler = null;
      }
    };
    const savePendingHotkey = async () => {
      detachRecorder();
      recordBtn.textContent = "Record";
      if (!pendingHotkey) return;
      this.plugin.settings[settingKey] = pendingHotkey;
      await this.plugin.saveSettings();
      this.plugin.registerSavedHotkeys();
      display.textContent = hotkeyLabel(pendingHotkey);
      new import_obsidian.Notice(`\u2705 ${label} set to ${hotkeyLabel(pendingHotkey)}`);
      pendingHotkey = null;
    };
    const recordBtn = row.controlEl.createEl("button", { text: "Record" });
    recordBtn.style.marginLeft = "8px";
    recordBtn.onclick = async () => {
      if (recording) {
        await savePendingHotkey();
        return;
      }
      recording = true;
      pendingHotkey = null;
      this.plugin.isRecordingHotkey = true;
      recordBtn.textContent = "Stop recording";
      recordBtn.classList.add("mod-warning");
      display.textContent = "Press keybind\u2026";
      keyHandler = (e) => {
        if (e.key === "Escape") {
          e.preventDefault();
          e.stopPropagation();
          e.stopImmediatePropagation();
          pendingHotkey = null;
          display.textContent = hotkeyLabel(this.plugin.settings[settingKey]);
          detachRecorder();
          recordBtn.textContent = "Record";
          return;
        }
        const hk = eventToHotkey(e);
        if (!hk) return;
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        pendingHotkey = hk;
        display.textContent = hotkeyLabel(hk);
      };
      document.addEventListener("keydown", keyHandler, true);
      document.addEventListener("keyup", keyHandler, true);
      window.addEventListener("keydown", keyHandler, true);
      window.addEventListener("keyup", keyHandler, true);
    };
    const clearBtn = row.controlEl.createEl("button", { text: "Clear" });
    clearBtn.style.marginLeft = "6px";
    clearBtn.onclick = async () => {
      detachRecorder();
      recordBtn.textContent = "Record";
      pendingHotkey = null;
      this.plugin.settings[settingKey] = null;
      await this.plugin.saveSettings();
      this.plugin.registerSavedHotkeys();
      display.textContent = hotkeyLabel(null);
    };
  }
};
